### ISSUE TITLE
f16

### ISSUE THREAD

**Issue by dtolnay** [jswrenn/fsize#2]
For `target_pointer_width = "16"` this might be a reasonable way to handle it, if someone needs:

```toml
# Cargo.toml

[target.'cfg(target_pointer_width = "16")'.dependencies]
half = "2"
```

```rust
// lib.rs

#[cfg(target_pointer_width = "16")]
pub type fsize = half::f16;
```

This is zero cost to anyone not on a 16-bit architecture, since Cargo won't even download or build the `half` crate there.
